services:
  pelican:
    image: 'ghcr.io/astral-sh/uv:debian'
    restart: unless-stopped
    volumes:
      - '.:/base'
    ports:
      - '8000:8000'
    working_dir: '/base'
    command: 'make serve'
    stdin_open: true
    tty: true
